if(WIN32)
	add_definitions(-lstdc++ -ldl)
	add_definitions(-DCPU_ONLY)
	
	###HDF5
	FIND_PACKAGE(HDF5 COMPONENTS C CXX HL REQUIRED)
	set(HDF5_INCLUDE_DIRS ${HDF5_DIR}/../../include)	
	set(HDF5_LIB_DIR ${HDF5_DIR}/../../lib)
	list(APPEND DEPENDENCY_INCLUDE_DIRS PUBLIC ${HDF5_INCLUDE_DIRS})
	list(APPEND DEPENDENCY_LINKER_DEBUG_LIBS ${HDF5_LIB_DIR}/libszip_D.lib)
	list(APPEND DEPENDENCY_LINKER_DEBUG_LIBS ${HDF5_LIB_DIR}/libzlib_D.lib)
	list(APPEND DEPENDENCY_LINKER_DEBUG_LIBS ${HDF5_LIB_DIR}/libhdf5_D.lib)
	list(APPEND DEPENDENCY_LINKER_DEBUG_LIBS ${HDF5_LIB_DIR}/libhdf5_cpp_D.lib)
	list(APPEND DEPENDENCY_LINKER_DEBUG_LIBS ${HDF5_LIB_DIR}/libhdf5_hl_D.lib)
	list(APPEND DEPENDENCY_LINKER_DEBUG_LIBS ${HDF5_LIB_DIR}/libhdf5_hl_cpp_D.lib)
	list(APPEND DEPENDENCY_LINKER_RELEASE_LIBS ${HDF5_LIB_DIR}/libszip_D.lib)
	list(APPEND DEPENDENCY_LINKER_RELEASE_LIBS ${HDF5_LIB_DIR}/libzlib_D.lib)
	list(APPEND DEPENDENCY_LINKER_RELEASE_LIBS ${HDF5_LIB_DIR}/libhdf5_D.lib)
	list(APPEND DEPENDENCY_LINKER_RELEASE_LIBS ${HDF5_LIB_DIR}/libhdf5_cpp_D.lib)
	list(APPEND DEPENDENCY_LINKER_RELEASE_LIBS ${HDF5_LIB_DIR}/libhdf5_hl_D.lib)
	list(APPEND DEPENDENCY_LINKER_RELEASE_LIBS ${HDF5_LIB_DIR}/libhdf5_hl_cpp_D.lib)
	
	
endif(WIN32)


