if(WIN32)
	add_definitions(-lstdc++ -ldl)
	add_definitions(-DCPU_ONLY)

	#set(CV_LIBRARIES_DIR C:/Work/Project/caffe-windows-ms/windows/thirdparty/OpenCV/x64/vc14/lib CACHE PATH "OPencv Lib path")
	#set(CV_INCLUDE_DIRS C:/Work/Project/caffe-windows-ms/windows/thirdparty/OpenCV/include CACHE PATH "Opencv Include ")
	#list(APPEND DEPENDENCY_INCLUDE_DIRS PUBLIC ${CV_INCLUDE_DIRS})
	#list(APPEND DEPENDENCY_LINKER_DEBUG_LIBS ${CV_LIBRARIES_DIR}/opencv_world310d.lib)
	#list(APPEND DEPENDENCY_LINKER_RELEASE_LIBS ${CV_LIBRARIES_DIR}/opencv_world310.lib)
	
	###Libraw
	set(LIBRAW_DIR " " CACHE PATH "LIB raw root directory")
	set(LIBRAW_INCLUDE_DIR ${LIBRAW_DIR}/libraw)
	set(LIBRAW_LIB_DIR ${LIBRAW_DIR}/build)
	list(APPEND DEPENDENCY_INCLUDE_DIRS PUBLIC ${LIBRAW_INCLUDE_DIR})
	list(APPEND DEPENDENCY_LINKER_DEBUG_LIBS ${LIBRAW_LIB_DIR}/Debug/raw.lib)
	list(APPEND DEPENDENCY_LINKER_RELEASE_LIBS ${LIBRAW_LIB_DIR}/Release/raw.lib)
	
	
	###HDF5
	FIND_PACKAGE(HDF5 COMPONENTS C CXX HL REQUIRED)
	set(HDF5_INCLUDE_DIRS ${HDF5_DIR}/../../include)	
	set(HDF5_LIB_DIR ${HDF5_DIR}/../../lib)
	list(APPEND DEPENDENCY_INCLUDE_DIRS PUBLIC ${HDF5_INCLUDE_DIRS})
	list(APPEND DEPENDENCY_LINKER_DEBUG_LIBS ${HDF5_LIB_DIR}/libszip_D.lib)
	list(APPEND DEPENDENCY_LINKER_DEBUG_LIBS ${HDF5_LIB_DIR}/libzlib_D.lib)
	list(APPEND DEPENDENCY_LINKER_DEBUG_LIBS ${HDF5_LIB_DIR}/libhdf5_D.lib)
	list(APPEND DEPENDENCY_LINKER_DEBUG_LIBS ${HDF5_LIB_DIR}/libhdf5_cpp_D.lib)
	list(APPEND DEPENDENCY_LINKER_DEBUG_LIBS ${HDF5_LIB_DIR}/libhdf5_hl_D.lib)
	list(APPEND DEPENDENCY_LINKER_DEBUG_LIBS ${HDF5_LIB_DIR}/libhdf5_hl_cpp_D.lib)
	list(APPEND DEPENDENCY_LINKER_RELEASE_LIBS ${HDF5_LIB_DIR}/libszip_D.lib)
	list(APPEND DEPENDENCY_LINKER_RELEASE_LIBS ${HDF5_LIB_DIR}/libzlib_D.lib)
	list(APPEND DEPENDENCY_LINKER_RELEASE_LIBS ${HDF5_LIB_DIR}/libhdf5_D.lib)
	list(APPEND DEPENDENCY_LINKER_RELEASE_LIBS ${HDF5_LIB_DIR}/libhdf5_cpp_D.lib)
	list(APPEND DEPENDENCY_LINKER_RELEASE_LIBS ${HDF5_LIB_DIR}/libhdf5_hl_D.lib)
	list(APPEND DEPENDENCY_LINKER_RELEASE_LIBS ${HDF5_LIB_DIR}/libhdf5_hl_cpp_D.lib)
	
	
endif(WIN32)


